apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "r8r.fullname" . }}
  labels:
    {{- include "r8r.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    jnnkrdb.de/src: github.com/jnnkrdb/r8r
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- . | toYaml | nindent 8 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "r8r.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations .Values.pod.annotations) ) | nindent 8 }}
      labels:
        {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels .Values.pod.labels) ) | nindent 8 }}
        {{- include "r8r.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: sa-{{ include "r8r.fullname" . }}
      {{- include "common.images.pullSecrets" ( dict "images" (list .Values.image) "global" .Values.global) | nindent 6 }}
      {{- with .Values.pod.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.pod.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}   
      {{- with .Values.pod.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.pod.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with (concat .Values.pod.extraVolumes .Values.global.extraVolumes) }}
      volumes:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      containers:
        {{- with .Values.pod.sidecarContainers }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        - name: r8r
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global "chart" .Chart ) }}
          imagePullPolicy: {{ include "common.images.pullPolicy" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          {{- with .Values.pod.containers.r8r.command }}
          command: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.r8r.args }}
          args: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.r8r.securityContext }}
          securityContext: 
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.containers.r8r.workingDir }}
          workingDir: {{ . | quote }}
          {{- end }}
          {{- with .Values.pod.containers.r8r.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP 
            - name: metrics
              containerPort: 8443
              protocol: TCP 
          {{- with (concat .Values.pod.containers.r8r.extraVolumeMounts 
                            .Values.pod.extraVolumeMounts 
                            .Values.global.extraVolumeMounts) }}
          volumeMounts:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with (concat .Values.pod.containers.r8r.extraEnvFrom .Values.pod.extraEnvFrom) }}
          envFrom:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with (concat .Values.pod.containers.r8r.extraEnvs .Values.pod.extraEnvs) }}
          env:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.pod.containers.r8r.healthz }}
          startupProbe:
            httpGet:
              path: /healthz
              port: health
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- end }}