# This rule is not used by the project r8r itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cluster.jnnkrdb.de.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: r8r
    app.kubernetes.io/managed-by: kustomize
  name: clusterobject-editor-role
rules:
- apiGroups:
  - cluster.jnnkrdb.de
  resources:
  - clusterobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.jnnkrdb.de
  resources:
  - clusterobjects/status
  verbs:
  - get
