apiVersion: cluster.jnnkrdb.de/v1alpha1
kind: ClusterObject
metadata:
  labels:
    app.kubernetes.io/name: r8r
    app.kubernetes.io/managed-by: kustomize
  name: clusterobject-sample-4
replicator:
  labelSelector:
    matchExpressions:
      - key: jnnkrdb.de/inherit
        operator: In
        values:
          - clusterobject-sample-4
  resource:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-cm-4
    data:
      test-data: This is a test
