apiVersion: cluster.jnnkrdb.de/v1alpha1
kind: ClusterObject
metadata:
  labels:
    app.kubernetes.io/name: echosec
    app.kubernetes.io/managed-by: kustomize
  name: clusterobject-sample
spec:
  # TODO(user): Add fields here
