apiVersion: cluster.jnnkrdb.de/v1alpha1
kind: ClusterObject
metadata:
  labels:
    app.kubernetes.io/name: echosec
    app.kubernetes.io/managed-by: kustomize
  name: clusterobject-sample-6
labelSelector:
  matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
resource:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: test-cm-6
  data:
    test-data: This is a test
