apiVersion: cluster.jnnkrdb.de/v1alpha1
kind: ClusterObject
metadata:
  labels:
    app.kubernetes.io/name: r8r
    app.kubernetes.io/managed-by: kustomize
  name: clusterobject-sample-1
replicator:
  resource:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-cm-1
    data:
      test-data: This is a test
