apiVersion: cluster.jnnkrdb.de/v1alpha1
kind: ClusterSecret
metadata:
  labels:
    app.kubernetes.io/name: echosec
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-sample
spec:
  # TODO(user): Add fields here
