---
apiVersion: cluster.jnnkrdb.de/v1alpha1
kind: ClusterSecret
metadata:
  labels:
    app.kubernetes.io/name: echosec
    app.kubernetes.io/managed-by: kustomize
  name: sample-0
spec:
  namespaceRegexRules:
    avoid:
      - kube-*
    match:
      - '.*'
  type: Opaque
  stringData:
    stringData_testValue: testValue
  data:
    data_testValue: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JRzJBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQklHZU1JR2JBZ0VCQkRDNWUvZkwyRVBTQUVibmFhN1cKYlBkZ2k1WEo3M0tZT1pWWmRYSFcvRVhUU3RscURpeXdOaDVnOTVqZWhkZFNFU09oWkFOaUFBU2VqdjVnWllQVApudk0zdEJhQjNxcXRGQklScVo5NG5aMll5b2YyUHBBYjZCYzNCUU0xOUp4L1R0bW91SWk0ZURIL3RPQTNIVEpiCitNQk5qRUluV250bm9HMnBxYWZia0ZQbmVTQjgzNXMyWVlBbm0vdjZDU2RwMkIvWGVHRm1aQUE9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
