## Append samples of your project ##
resources:
  - cluster_v1alpha1_clusterobject-0.yaml
  - cluster_v1alpha1_clusterobject-1.yaml
  - cluster_v1alpha1_clusterobject-2.yaml
  - cluster_v1alpha1_clusterobject-3.yaml
  - cluster_v1alpha1_clusterobject-4.yaml
  - cluster_v1alpha1_clusterobject-5.yaml
  - cluster_v1alpha1_clusterobject-6.yaml

# +kubebuilder:scaffold:manifestskustomizesamples
