name: Build and Push Container Images

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.devcontainer/**'
      - '.charts/**'
      - 'README.md'
      - 'LICENSE'
      - 'VERSION'
  pull_request:
    branches: 
      - master 

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  GITVERSION_FILE: .github/gitversion/GitVersion.yml
  REPOSITORY: ghcr.io/jnnkrdb/echosec
  DOCKERFILE: ./Dockerfile
  VERSION_FILE: ./VERSION
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: ${{ env.GITVERSION_FILE }}

      - id: version
        run: echo "semver=${{ steps.gitversion.outputs.semVer }}" >> $GITHUB_OUTPUT
  
  build:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: bash-version
        run: |
          echo ${{ needs.version.outputs.semver }} > ${{ env.VERSION_FILE }}
          echo $(cat ${{ env.VERSION_FILE }})

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHP_TOKEN }}

      - name: Build Image Push
        uses: docker/build-push-action@v5
        with:
          context: "."
          file: ${{ env.DOCKERFILE }}
          tags: |
            ${{ env.REPOSITORY }}:mgr.${{ env.BRANCH_NAME }}
            ${{ env.REPOSITORY }}:mgr.${{ needs.version.outputs.semver }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            VERSION=${{ needs.version.outputs.semver }}
            BRANCH=${{ env.BRANCH_NAME }}
            
              
