name: Package Helmchart

on:
  push:
    branches:
      - master
      - dev
    paths:
      - '.github/workflows/create-helmchart.yaml'
      - '.helm/**'
  pull_request:
    branches: 
      - master 

env:
  GITVERSION_FILE: .github/gitversion/GitVersion.yml
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  HELM_DIR: .helm/

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: ${{ env.GITVERSION_FILE }}

      - id: version
        run: echo "semver=${{ steps.gitversion.outputs.semVer }}" >> $GITHUB_OUTPUT

  helm:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
       
      - name: Update Dependencies
        run: helm dependency update ${{ env.HELM_DIR }} --debug

      - name: Lint
        run: helm lint ${{ env.HELM_DIR }} --debug
        
      - name: Validate
        uses: nlamirault/helm-kubeconform-action@v0.1.0
        with:
          charts: ${{ env.HELM_DIR }}

      #- name: Package
      #  run:  helm package ${{ env.HELM_DIR }} --version ${{ needs.version.outputs.semver }}

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: echosec
          repository: jnnkrdb
          tag: ${{ needs.version.outputs.semver }}
          path: ${{ env.HELM_DIR }} # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHP_TOKEN }}
          update_dependencies: 'true' # Defaults to false

# helm pull ghcr.io/appany/my-chart:0.1.0
