name: Prebuild DevContainer

on:
  push:
    branches: 
      - master
    paths:
      - '.devcontainer/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHP_TOKEN }}

      - name: Create './kube' Directory
        run: mkdir -p ~/.kube

      - name: Build DevContainer and Run Tests
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/jnnkrdb/operator-devcontainer:echosec
          runCmd: |
            kubebuilder version
            minikube version
            kubectl version
            helm version
            k9s version
            go version